package calculator;

import java.awt.Image;
import javax.script.ScriptEngineManager;
import javax.script.ScriptEngine;
import javax.script.ScriptException;


public class GUI extends javax.swing.JFrame {

    private String expression = new String();
    
    public GUI() {
        initComponents();
    }
    
    private Image setIcon(){
        return getToolkit().getImage("resources\\icon.png");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        expressionTextField = new javax.swing.JTextField();
        clearButton = new javax.swing.JButton();
        number7 = new javax.swing.JButton();
        number4 = new javax.swing.JButton();
        number2 = new javax.swing.JButton();
        rightParenthesis = new javax.swing.JButton();
        leftParenthesis = new javax.swing.JButton();
        number8 = new javax.swing.JButton();
        number1 = new javax.swing.JButton();
        number5 = new javax.swing.JButton();
        number9 = new javax.swing.JButton();
        number6 = new javax.swing.JButton();
        number3 = new javax.swing.JButton();
        delButton = new javax.swing.JButton();
        number0 = new javax.swing.JButton();
        decimal = new javax.swing.JButton();
        division = new javax.swing.JButton();
        multiplication = new javax.swing.JButton();
        subtraction = new javax.swing.JButton();
        addition = new javax.swing.JButton();
        evaluation = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setIconImage(setIcon());
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        expressionTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                expressionTextFieldKeyTyped(evt);
            }
        });

        clearButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        clearButton.setText("C");
        clearButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearButtonMouseClicked(evt);
            }
        });
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        number7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        number7.setText("7");
        number7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                number7MouseClicked(evt);
            }
        });

        number4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        number4.setText("4");
        number4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                number4MouseClicked(evt);
            }
        });

        number2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        number2.setText("2");
        number2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                number2MouseClicked(evt);
            }
        });

        rightParenthesis.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rightParenthesis.setText(")");
        rightParenthesis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rightParenthesisMouseClicked(evt);
            }
        });

        leftParenthesis.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        leftParenthesis.setText("(");
        leftParenthesis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                leftParenthesisMouseClicked(evt);
            }
        });

        number8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        number8.setText("8");
        number8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                number8MouseClicked(evt);
            }
        });

        number1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        number1.setText("1");
        number1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                number1MouseClicked(evt);
            }
        });

        number5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        number5.setText("5");
        number5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                number5MouseClicked(evt);
            }
        });

        number9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        number9.setText("9");
        number9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                number9MouseClicked(evt);
            }
        });

        number6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        number6.setText("6");
        number6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                number6MouseClicked(evt);
            }
        });

        number3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        number3.setText("3");
        number3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                number3MouseClicked(evt);
            }
        });

        delButton.setBackground(new java.awt.Color(255, 51, 51));
        delButton.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        delButton.setText("DEL");
        delButton.setContentAreaFilled(false);
        delButton.setOpaque(true);
        delButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delButtonMouseClicked(evt);
            }
        });

        number0.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        number0.setText("0");
        number0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                number0MouseClicked(evt);
            }
        });

        decimal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        decimal.setText(".");
        decimal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                decimalMouseClicked(evt);
            }
        });

        division.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        division.setText("/");
        division.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                divisionMouseClicked(evt);
            }
        });

        multiplication.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        multiplication.setText("x");
        multiplication.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                multiplicationMouseClicked(evt);
            }
        });

        subtraction.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        subtraction.setText("-");
        subtraction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subtractionMouseClicked(evt);
            }
        });

        addition.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addition.setText("+");
        addition.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                additionMouseClicked(evt);
            }
        });

        evaluation.setBackground(new java.awt.Color(0, 255, 0));
        evaluation.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        evaluation.setText("=");
        evaluation.setContentAreaFilled(false);
        evaluation.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        evaluation.setOpaque(true);
        evaluation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                evaluationMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(expressionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(number1)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(clearButton, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(number7))
                                        .addComponent(number4)))
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(delButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(number0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(number2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(number5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(number8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(leftParenthesis, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(decimal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(number6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rightParenthesis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(number9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(number3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(division, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(multiplication, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(evaluation, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(addition, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(subtraction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(expressionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearButton)
                    .addComponent(leftParenthesis)
                    .addComponent(rightParenthesis)
                    .addComponent(division))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(number7)
                    .addComponent(number8)
                    .addComponent(number9)
                    .addComponent(multiplication))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(number6)
                    .addComponent(number5)
                    .addComponent(number4)
                    .addComponent(subtraction))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(number1)
                    .addComponent(number2)
                    .addComponent(number3)
                    .addComponent(addition))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(decimal)
                    .addComponent(number0)
                    .addComponent(delButton)
                    .addComponent(evaluation))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void clearButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearButtonMouseClicked
        // TODO add your handling code here:
        expression = "";
        expressionTextField.setText(expression);
    }//GEN-LAST:event_clearButtonMouseClicked

    private void number7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number7MouseClicked
        // TODO add your handling code here:
        expression += "7";
        expressionTextField.setText(expression);
    }//GEN-LAST:event_number7MouseClicked

    private void number8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number8MouseClicked
        // TODO add your handling code here:
        expression += "8";
        expressionTextField.setText(expression);
    }//GEN-LAST:event_number8MouseClicked

    private void number9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number9MouseClicked
        // TODO add your handling code here:
        expression += "9";
        expressionTextField.setText(expression);
    }//GEN-LAST:event_number9MouseClicked

    private void number4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number4MouseClicked
        // TODO add your handling code here:
        expression += "4";
        expressionTextField.setText(expression);
    }//GEN-LAST:event_number4MouseClicked

    private void number5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number5MouseClicked
        // TODO add your handling code here:
        expression += "5";
        expressionTextField.setText(expression);
    }//GEN-LAST:event_number5MouseClicked

    private void number6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number6MouseClicked
        // TODO add your handling code here:
        expression += "6";
        expressionTextField.setText(expression);
    }//GEN-LAST:event_number6MouseClicked

    private void number1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number1MouseClicked
        // TODO add your handling code here:
        expression += "1";
        expressionTextField.setText(expression);
    }//GEN-LAST:event_number1MouseClicked

    private void number2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number2MouseClicked
        // TODO add your handling code here:
        expression += "2";
        expressionTextField.setText(expression);
    }//GEN-LAST:event_number2MouseClicked

    private void number3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number3MouseClicked
        // TODO add your handling code here:
        expression += "3";
        expressionTextField.setText(expression);
    }//GEN-LAST:event_number3MouseClicked

    private void rightParenthesisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rightParenthesisMouseClicked
        // TODO add your handling code here:
        expression += ")";
        expressionTextField.setText(expression);
    }//GEN-LAST:event_rightParenthesisMouseClicked

    private void divisionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divisionMouseClicked
        // TODO add your handling code here:
        expression += "/";
        expressionTextField.setText(expression);
    }//GEN-LAST:event_divisionMouseClicked

    private void multiplicationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiplicationMouseClicked
        // TODO add your handling code here:
        expression += "*";
        expressionTextField.setText(expression);
    }//GEN-LAST:event_multiplicationMouseClicked

    private void subtractionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subtractionMouseClicked
        // TODO add your handling code here:
        expression += "-";
        expressionTextField.setText(expression);
    }//GEN-LAST:event_subtractionMouseClicked

    private void additionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_additionMouseClicked
        // TODO add your handling code here:
        expression += "+";
        expressionTextField.setText(expression);
    }//GEN-LAST:event_additionMouseClicked

    private void number0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number0MouseClicked
        // TODO add your handling code here:
        expression += "0";
        expressionTextField.setText(expression);
    }//GEN-LAST:event_number0MouseClicked

    private void decimalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decimalMouseClicked
        // TODO add your handling code here:
        expression += ".";
        expressionTextField.setText(expression);
    }//GEN-LAST:event_decimalMouseClicked

    private void delButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delButtonMouseClicked
        // TODO add your handling code here:
        if (expression!="")
        {
            expression = expression.substring(0, expression.length()-1);
            expressionTextField.setText(expression);
        }
    }//GEN-LAST:event_delButtonMouseClicked

    private void leftParenthesisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leftParenthesisMouseClicked
        // TODO add your handling code here:
        expression += "(";
        expressionTextField.setText(expression);
    }//GEN-LAST:event_leftParenthesisMouseClicked

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearButtonActionPerformed

    private void evaluationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_evaluationMouseClicked
        // TODO add your handling code here:
        ScriptEngineManager mgr = new ScriptEngineManager();
        ScriptEngine engine = mgr.getEngineByName("JavaScript");
        
        try {
            expression = engine.eval(expressionTextField.getText()).toString();
            expressionTextField.setText(expression);
        } catch (ScriptException e) {
            expression = "";
            expressionTextField.setText("SYNTAX ERROR");
        }
    }//GEN-LAST:event_evaluationMouseClicked

    private void expressionTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_expressionTextFieldKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ( ((c < '0') || (c > '9')) && (c!='+')
                && (c!='-') && (c!='*') && (c!='/') && (c!='(') && (c!=')')){
            evt.consume();  // ignore event
        }
    }//GEN-LAST:event_expressionTextFieldKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addition;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton decimal;
    private javax.swing.JButton delButton;
    private javax.swing.JButton division;
    private javax.swing.JButton evaluation;
    private javax.swing.JTextField expressionTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton leftParenthesis;
    private javax.swing.JButton multiplication;
    private javax.swing.JButton number0;
    private javax.swing.JButton number1;
    private javax.swing.JButton number2;
    private javax.swing.JButton number3;
    private javax.swing.JButton number4;
    private javax.swing.JButton number5;
    private javax.swing.JButton number6;
    private javax.swing.JButton number7;
    private javax.swing.JButton number8;
    private javax.swing.JButton number9;
    private javax.swing.JButton rightParenthesis;
    private javax.swing.JButton subtraction;
    // End of variables declaration//GEN-END:variables
}
